### ISSUE TITLE
parserの調整

### ISSUE THREAD

**Issue by yu-432** [oonisidesu/cub3D#66]
aaa

**Comment by yu-432** [comment]
12/17
is_prefix_and_whitespaceをすべてft_strncmpに置換した。
strncmpを通過したあと、tabを許容した処理が残っているのでこの部分を修正する必要があるかもしれない。動作はしている。
テストケースとして
- テクスチャネームとpathとの間がtabの場合
- mapにtabが含まれる場合1
- mapにtabが含まれる場合2
- tabのみの行が含まれる場合
を作成した

**Comment by yu-432** [comment]
parseエラーが発生した場合に、一度ウィンドウが表示されるのが少し気になったけど、終了してプレイ可能ではないので問題ない

**Comment by oonisidesu** [comment]
> parseエラーが発生した場合に、一度ウィンドウが表示されるのが少し気になったけど、終了してプレイ可能ではないので問題ない

これ、parseする前にmlx初期化してしまっているからっぽいですね。。。
余裕があれば修正しておきたいですね。。。

**Comment by yu-432** [comment]
## Task
- [ ] parse_cub_file -> process_file_lines -> read_and_trim_line -> ft_strtrim_r関数の削除
- [ ] map/error/SPACE_TAB4.cub このケースがエラーになるか確認
- [ ] parse_comma関数の更新
- [ ] parse_color_value関数の更新
- [ ] set_player_position関数の階層を浅くする

**Comment by yu-432** [comment]
trim関数を削除した

結果ファイルパスに付随するtab,spaceもファイルパスとして認識されopenで失敗するようになる。
gnlでlineの最後が'\n'で帰ってくるため'\0'に変更する処理がを追加した。
テクスチャと認識する条件を"NO(space)"から"NO"に変更し、テクスチャを処理する関数内部でtabのチェックをするように変更した。->テクスチャ関数のエラーとして出力されるようになる。
　変更しない場合
　`Missing element in .cub file`
　変更した場合
　`Failed to parse texture line`

**Comment by yu-432** [comment]
parse_comma関数の更新
 parse_color_value関数の更新
 set_player_position関数の階層を浅くする
 
 完了
